---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
    attributes:
      mu:
        emacs_package: emacs23-nox
  - name: debian-8
    attributes:
      mu:
        emacs_package: emacs24-nox

suites:
  - name: default
    run_list:
      - recipe[mu]
  - name: compile
    run_list:
      - recipe[mu]
    attributes:
      mu:
        packages: []
