---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.2
    driver_config:
      box: opscode_debian-7.2.0_chef-provisionerless.box
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

suites:
- name: default
  run_list:
  - recipe[mu]
- name: compile
  run_list:
  - recipe[mu::compile]
  attributes: {
    mu: {
      compile: {
        build_dir: '/opt/mu'
      }
    }
  }
